[project]
name = "soft-actor-critic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.2",
    "numpy>=2.3.5",
    "torch>=2.9.1",
    "torchrl>=0.10.1",
]
